In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [2]:
df = pd.read_csv("C:\\Users\\s\\Desktop\\WETHER\\weather_dataset.csv")
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [3]:
df.drop(["date"], inplace=True, axis=1)

In [4]:
df.head()

   precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7  drizzle
1           10.9      10.6       2.8   4.5     rain
2            0.8      11.7       7.2   2.3     rain
3           20.3      12.2       5.6   4.7     rain
4            1.3       8.9       2.8   6.1     rain

In [5]:
df.shape

(1461, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   precipitation  1461 non-null   float64
 1   temp_max       1461 non-null   float64
 2   temp_min       1461 non-null   float64
 3   wind           1461 non-null   float64
 4   weather        1461 non-null   object
dtypes: float64(4), object(1)
memory usage: 57.2+ KB

In [7]:
df.describe()

       precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [8]:
df[["weather"]].value_counts()

weather
rain       641
sun        640
fog        101
drizzle     53
snow        26
Name: count, dtype: int64

In [9]:
df.isna().sum()

precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

In [10]:
df.weather = df.weather.replace({"drizzle": 0, "rain": 1, "sun": 2, "snow": 3, "fog": 4})

C:\Users\s\AppData\Local\Temp\ipykernel_12592\2064994455.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.weather = df.weather.replace({"drizzle": 0, "rain": 1, "sun": 2, "snow": 3, "fog": 4})

In [11]:
df_0 = df[df['weather']==0]
df_1 = df[df['weather']==1]
df_2 = df[df['weather']==2]
df_3 = df[df['weather']==3]
df_4 = df[df['weather']==4]

df_0 = df_0.sample(26)
df_1 = df_1.sample(26)
df_2 = df_2.sample(26)
df_3 = df_3.sample(26)
df_4 = df_4.sample(26)

df_balanced = pd.concat([df_0, df_1, df_2, df_3, df_4])

In [12]:
df_balanced.head()

      precipitation  temp_max  temp_min  wind  weather
191             0.0      23.9      11.1   2.3        0
387             0.0       3.3      -1.7   0.6        0
1374            0.0      18.3      10.0   2.6        0
1282            0.0      29.4      15.6   3.2        0
263             0.0      19.4      10.0   2.5        0

In [13]:
df_balanced.shape

(130, 5)

In [14]:
import numpy as np

In [15]:
row_1 = np.array(["Drizzle", 26])
row_2 = np.array(["Rain", 26])
row_3 = np.array(["Sun", 26])
row_4 = np.array(["Snow", 26])
row_5 = np.array(["Fog", 26])

data = pd.DataFrame([row_1], columns=["Weather", "Number of that Class"])

data.loc[len(data.index)] = row_2
data.loc[len(data.index)] = row_3
data.loc[len(data.index)] = row_4
data.loc[len(data.index)] = row_5

In [16]:
data

   Weather Number of that Class
0  Drizzle                   26
1     Rain                   26
2      Sun                   26
3     Snow                   26
4      Fog                   26

In [17]:
data.to_csv("C:\\Users\\s\\Desktop\\WETHER\\weather_classes.csv")

In [18]:
X = df_balanced.iloc[:, 0:-1]
y = df_balanced.iloc[:, -1]

In [19]:
X.head()

      precipitation  temp_max  temp_min  wind
191             0.0      23.9      11.1   2.3
387             0.0       3.3      -1.7   0.6
1374            0.0      18.3      10.0   2.6
1282            0.0      29.4      15.6   3.2
263             0.0      19.4      10.0   2.5

In [20]:
y.head()

191     0
387     0
1374    0
1282    0
263     0
Name: weather, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=16)

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [26]:
y_predicted = knn_model.predict(X_test)

In [27]:
score = knn_model.score(X_test, y_test)

print('accuracy_score overall :', score)
print('accuracy_score percent :', round(score*100,2))

accuracy_score overall : 0.46153846153846156
accuracy_score percent : 46.15

In [28]:
from sklearn.metrics import classification_report

In [29]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.22      0.50      0.31         4
           1       0.67      0.67      0.67         6
           2       0.00      0.00      0.00         7
           3       1.00      0.75      0.86         4
           4       1.00      0.60      0.75         5

    accuracy                           0.46        26
   macro avg       0.58      0.50      0.52        26
weighted avg       0.53      0.46      0.48        26

In [30]:
from sklearn.naive_bayes import GaussianNB

In [31]:
nb_model = GaussianNB()
nb_model = nb_model.fit(X_train, y_train)

In [32]:
y_pred = nb_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.14      0.25      0.18         4
           1       0.83      0.83      0.83         6
           2       0.20      0.14      0.17         7
           3       1.00      0.75      0.86         4
           4       0.20      0.20      0.20         5

    accuracy                           0.42        26
   macro avg       0.48      0.44      0.45        26
weighted avg       0.46      0.42      0.44        26

In [33]:
from sklearn.svm import SVC

In [34]:
svm_model = SVC()
svm_model = svm_model.fit(X_train, y_train)

In [35]:
y_pred = svm_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.21      0.75      0.33         4
           1       0.33      0.17      0.22         6
           2       0.00      0.00      0.00         7
           3       1.00      0.50      0.67         4
           4       0.14      0.20      0.17         5

    accuracy                           0.27        26
   macro avg       0.34      0.32      0.28        26
weighted avg       0.29      0.27      0.24        26

c:\Users\s\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\s\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\s\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [37]:
random_forest = RandomForestClassifier()

random_forest.fit(X_train, y_train)

RandomForestClassifier()

In [38]:
y_pred = random_forest.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.22      0.50      0.31         4
           1       0.83      0.83      0.83         6
           2       0.25      0.14      0.18         7
           3       1.00      0.75      0.86         4
           4       0.75      0.60      0.67         5

    accuracy                           0.54        26
   macro avg       0.61      0.57      0.57        26
weighted avg       0.59      0.54      0.55        26

In [40]:
import pickle as pkl
pkl.dump(scaler, open(f"C:\\Users\\s\\Desktop\\WETHER\\scaler.pkl", "wb"))

In [41]:
pkl.dump(knn_model, open(f"C:\\Users\\s\\Desktop\\WETHER\\weather_model.pkl", "wb"))